// <auto-generated />
namespace JabbR.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MessageTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201304140935434_MessageTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
