//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/3/2011 10:44:25 AM
namespace JabbR.NerdDinnersServiceDataContext
{
    
    /// <summary>
    /// There are no comments for NerdDinners in the schema.
    /// </summary>
    public partial class NerdDinners : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NerdDinners object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NerdDinners(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("NerdDinner.Models", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("JabbR.NerdDinnersServiceDataContext", typeName.Substring(17)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("JabbR.NerdDinnersServiceDataContext", global::System.StringComparison.Ordinal))
            {
                return string.Concat("NerdDinner.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Dinners in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Dinner> Dinners
        {
            get
            {
                if ((this._Dinners == null))
                {
                    this._Dinners = base.CreateQuery<Dinner>("Dinners");
                }
                return this._Dinners;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Dinner> _Dinners;
        /// <summary>
        /// There are no comments for RSVPs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSVP> RSVPs
        {
            get
            {
                if ((this._RSVPs == null))
                {
                    this._RSVPs = base.CreateQuery<RSVP>("RSVPs");
                }
                return this._RSVPs;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSVP> _RSVPs;
        /// <summary>
        /// There are no comments for Dinners in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDinners(Dinner dinner)
        {
            base.AddObject("Dinners", dinner);
        }
        /// <summary>
        /// There are no comments for RSVPs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRSVPs(RSVP rSVP)
        {
            base.AddObject("RSVPs", rSVP);
        }
    }
    /// <summary>
    /// There are no comments for ComplexType NerdDinner.Models.LocationDetail in the schema.
    /// </summary>
    public partial class LocationDetail
    {
    }
    /// <summary>
    /// There are no comments for NerdDinner.Models.Dinner in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DinnerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("DinnerID")]
    public partial class Dinner
    {
        /// <summary>
        /// Create a new Dinner object.
        /// </summary>
        /// <param name="dinnerID">Initial value of DinnerID.</param>
        /// <param name="eventDate">Initial value of EventDate.</param>
        /// <param name="latitude">Initial value of Latitude.</param>
        /// <param name="longitude">Initial value of Longitude.</param>
        /// <param name="location">Initial value of Location.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Dinner CreateDinner(int dinnerID, global::System.DateTime eventDate, double latitude, double longitude, LocationDetail location)
        {
            Dinner dinner = new Dinner();
            dinner.DinnerID = dinnerID;
            dinner.EventDate = eventDate;
            dinner.Latitude = latitude;
            dinner.Longitude = longitude;
            if ((location == null))
            {
                throw new global::System.ArgumentNullException("location");
            }
            dinner.Location = location;
            return dinner;
        }
        /// <summary>
        /// There are no comments for Property DinnerID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DinnerID
        {
            get
            {
                return this._DinnerID;
            }
            set
            {
                this.OnDinnerIDChanging(value);
                this._DinnerID = value;
                this.OnDinnerIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DinnerID;
        partial void OnDinnerIDChanging(int value);
        partial void OnDinnerIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property EventDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EventDate
        {
            get
            {
                return this._EventDate;
            }
            set
            {
                this.OnEventDateChanging(value);
                this._EventDate = value;
                this.OnEventDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EventDate;
        partial void OnEventDateChanging(global::System.DateTime value);
        partial void OnEventDateChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property HostedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string HostedBy
        {
            get
            {
                return this._HostedBy;
            }
            set
            {
                this.OnHostedByChanging(value);
                this._HostedBy = value;
                this.OnHostedByChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _HostedBy;
        partial void OnHostedByChanging(string value);
        partial void OnHostedByChanged();
        /// <summary>
        /// There are no comments for Property ContactPhone in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContactPhone
        {
            get
            {
                return this._ContactPhone;
            }
            set
            {
                this.OnContactPhoneChanging(value);
                this._ContactPhone = value;
                this.OnContactPhoneChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContactPhone;
        partial void OnContactPhoneChanging(string value);
        partial void OnContactPhoneChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Latitude;
        partial void OnLatitudeChanging(double value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Longitude;
        partial void OnLongitudeChanging(double value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Property HostedById in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string HostedById
        {
            get
            {
                return this._HostedById;
            }
            set
            {
                this.OnHostedByIdChanging(value);
                this._HostedById = value;
                this.OnHostedByIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _HostedById;
        partial void OnHostedByIdChanging(string value);
        partial void OnHostedByIdChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LocationDetail Location
        {
            get
            {
                if (((this._Location == null) 
                            && (this._LocationInitialized != true)))
                {
                    this._Location = new LocationDetail();
                    this._LocationInitialized = true;
                }
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this._LocationInitialized = true;
                this.OnLocationChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private LocationDetail _Location;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _LocationInitialized;
        partial void OnLocationChanging(LocationDetail value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for RSVPs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<RSVP> RSVPs
        {
            get
            {
                return this._RSVPs;
            }
            set
            {
                if ((value != null))
                {
                    this._RSVPs = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<RSVP> _RSVPs = new global::System.Collections.ObjectModel.Collection<RSVP>();
    }
    /// <summary>
    /// There are no comments for NerdDinner.Models.RSVP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RsvpID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("RsvpID")]
    public partial class RSVP
    {
        /// <summary>
        /// Create a new RSVP object.
        /// </summary>
        /// <param name="rsvpID">Initial value of RsvpID.</param>
        /// <param name="dinnerID">Initial value of DinnerID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSVP CreateRSVP(int rsvpID, int dinnerID)
        {
            RSVP rSVP = new RSVP();
            rSVP.RsvpID = rsvpID;
            rSVP.DinnerID = dinnerID;
            return rSVP;
        }
        /// <summary>
        /// There are no comments for Property RsvpID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RsvpID
        {
            get
            {
                return this._RsvpID;
            }
            set
            {
                this.OnRsvpIDChanging(value);
                this._RsvpID = value;
                this.OnRsvpIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RsvpID;
        partial void OnRsvpIDChanging(int value);
        partial void OnRsvpIDChanged();
        /// <summary>
        /// There are no comments for Property DinnerID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DinnerID
        {
            get
            {
                return this._DinnerID;
            }
            set
            {
                this.OnDinnerIDChanging(value);
                this._DinnerID = value;
                this.OnDinnerIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DinnerID;
        partial void OnDinnerIDChanging(int value);
        partial void OnDinnerIDChanged();
        /// <summary>
        /// There are no comments for Property AttendeeName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AttendeeName
        {
            get
            {
                return this._AttendeeName;
            }
            set
            {
                this.OnAttendeeNameChanging(value);
                this._AttendeeName = value;
                this.OnAttendeeNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AttendeeName;
        partial void OnAttendeeNameChanging(string value);
        partial void OnAttendeeNameChanged();
        /// <summary>
        /// There are no comments for Property AttendeeNameId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AttendeeNameId
        {
            get
            {
                return this._AttendeeNameId;
            }
            set
            {
                this.OnAttendeeNameIdChanging(value);
                this._AttendeeNameId = value;
                this.OnAttendeeNameIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AttendeeNameId;
        partial void OnAttendeeNameIdChanging(string value);
        partial void OnAttendeeNameIdChanged();
        /// <summary>
        /// There are no comments for Dinner in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Dinner Dinner
        {
            get
            {
                return this._Dinner;
            }
            set
            {
                this._Dinner = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Dinner _Dinner;
    }
}
