//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JabbR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JabbR.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to make an admin?.
        /// </summary>
        internal static string AddAdmin_UserRequired {
            get {
                return ResourceManager.GetString("AddAdmin_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to add ownership to?.
        /// </summary>
        internal static string AddOwner_RoomRequired {
            get {
                return ResourceManager.GetString("AddOwner_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to make an owner?.
        /// </summary>
        internal static string AddOwner_UserRequired {
            get {
                return ResourceManager.GetString("AddOwner_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an admin..
        /// </summary>
        internal static string AdminRequired {
            get {
                return ResourceManager.GetString("AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to allow access to?.
        /// </summary>
        internal static string Allow_RoomRequired {
            get {
                return ResourceManager.GetString("Allow_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to grant access permissions to?.
        /// </summary>
        internal static string Allow_UserRequired {
            get {
                return ResourceManager.GetString("Allow_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to list the allowed users of?.
        /// </summary>
        internal static string Allowed_RoomRequired {
            get {
                return ResourceManager.GetString("Allowed_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support the audio tag..
        /// </summary>
        internal static string AudioTagSupportRequired {
            get {
                return ResourceManager.GetString("AudioTagSupportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} account has already been linked to another user..
        /// </summary>
        internal static string Authentication_AccountAlreadyLinked {
            get {
                return ResourceManager.GetString("Authentication_AccountAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully linked {0} account..
        /// </summary>
        internal static string Authentication_AccountLinkedSuccess {
            get {
                return ResourceManager.GetString("Authentication_AccountLinkedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string Authentication_EmailRequired {
            get {
                return ResourceManager.GetString("Authentication_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Check your username/password..
        /// </summary>
        internal static string Authentication_GenericFailure {
            get {
                return ResourceManager.GetString("Authentication_GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed your username..
        /// </summary>
        internal static string Authentication_NameChangeCompleted {
            get {
                return ResourceManager.GetString("Authentication_NameChangeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usernames don&apos;t match..
        /// </summary>
        internal static string Authentication_NameNonMatching {
            get {
                return ResourceManager.GetString("Authentication_NameNonMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        internal static string Authentication_NameRequired {
            get {
                return ResourceManager.GetString("Authentication_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not logged in..
        /// </summary>
        internal static string Authentication_NotLoggedIn {
            get {
                return ResourceManager.GetString("Authentication_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s already your username....
        /// </summary>
        internal static string Authentication_OldNewUsernamesSame {
            get {
                return ResourceManager.GetString("Authentication_OldNewUsernamesSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required..
        /// </summary>
        internal static string Authentication_OldPasswordRequired {
            get {
                return ResourceManager.GetString("Authentication_OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a password..
        /// </summary>
        internal static string Authentication_PassAddSuccess {
            get {
                return ResourceManager.GetString("Authentication_PassAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed your password..
        /// </summary>
        internal static string Authentication_PassChangeSuccess {
            get {
                return ResourceManager.GetString("Authentication_PassChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be at least {0} characters..
        /// </summary>
        internal static string Authentication_PassLengthRequired {
            get {
                return ResourceManager.GetString("Authentication_PassLengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match..
        /// </summary>
        internal static string Authentication_PassNonMatching {
            get {
                return ResourceManager.GetString("Authentication_PassNonMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Authentication_PassRequired {
            get {
                return ResourceManager.GetString("Authentication_PassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unlinked {0} account..
        /// </summary>
        internal static string Authentication_UnlinkCompleted {
            get {
                return ResourceManager.GetString("Authentication_UnlinkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot unlink this account because you would lose your ability to login..
        /// </summary>
        internal static string Authentication_UnlinkRequiresMultipleIdentities {
            get {
                return ResourceManager.GetString("Authentication_UnlinkRequiresMultipleIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity {0} already taken with Provider {1}, please login with a different provider/identity combination..
        /// </summary>
        internal static string AuthenticationIdentityProviderTaken {
            get {
                return ResourceManager.GetString("AuthenticationIdentityProviderTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required..
        /// </summary>
        internal static string AuthenticationPasswordRequired {
            get {
                return ResourceManager.GetString("AuthenticationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot ban another admin..
        /// </summary>
        internal static string Ban_CannotBanAdmin {
            get {
                return ResourceManager.GetString("Ban_CannotBanAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to ban?.
        /// </summary>
        internal static string Ban_UserRequired {
            get {
                return ResourceManager.GetString("Ban_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What message do you want to broadcast?.
        /// </summary>
        internal static string Broadcast_MessageRequired {
            get {
                return ResourceManager.GetString("Broadcast_MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to close?.
        /// </summary>
        internal static string Close_RoomRequired {
            get {
                return ResourceManager.GetString("Close_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ambiguous: {1}..
        /// </summary>
        internal static string CommandAmbiguous {
            get {
                return ResourceManager.GetString("CommandAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid command..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (click to show/hide).
        /// </summary>
        internal static string Content_HeaderAndToggle {
            get {
                return ResourceManager.GetString("Content_HeaderAndToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the country ISO code you requested doesn&apos;t exist. Please refer to http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 for a proper list of country ISO codes..
        /// </summary>
        internal static string CountryISOInvalid {
            get {
                return ResourceManager.GetString("CountryISOInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps.
        /// </summary>
        internal static string GoogleMapsContent_DefaultTitle {
            get {
                return ResourceManager.GetString("GoogleMapsContent_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which email address do you want to use for the Gravatar image?.
        /// </summary>
        internal static string Gravatar_EmailRequired {
            get {
                return ResourceManager.GetString("Gravatar_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t invite yourself!.
        /// </summary>
        internal static string Invite_CannotInviteSelf {
            get {
                return ResourceManager.GetString("Invite_CannotInviteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to invite them to?.
        /// </summary>
        internal static string Invite_RoomRequired {
            get {
                return ResourceManager.GetString("Invite_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to invite?.
        /// </summary>
        internal static string Invite_UserRequired {
            get {
                return ResourceManager.GetString("Invite_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only private rooms can have invite codes..
        /// </summary>
        internal static string InviteCode_PrivateRoomRequired {
            get {
                return ResourceManager.GetString("InviteCode_PrivateRoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to show the invite code for?.
        /// </summary>
        internal static string InviteCode_RoomRequired {
            get {
                return ResourceManager.GetString("InviteCode_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Code for {0}: {1}.
        /// </summary>
        internal static string InviteCode_Success {
            get {
                return ResourceManager.GetString("InviteCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be invoked from the Lobby..
        /// </summary>
        internal static string InvokeFromRoomRequired {
            get {
                return ResourceManager.GetString("InvokeFromRoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join {0}. This room is locked and you don&apos;t have permission to enter. If you have an invite code, enter it in the /join command.
        /// </summary>
        internal static string Join_LockedAccessPermission {
            get {
                return ResourceManager.GetString("Join_LockedAccessPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to join?.
        /// </summary>
        internal static string Join_RoomRequired {
            get {
                return ResourceManager.GetString("Join_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Me Meeting: {0}.
        /// </summary>
        internal static string JoinMeContent_DefaultTitle {
            get {
                return ResourceManager.GetString("JoinMeContent_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot kick an admin. Only admin can kick admin..
        /// </summary>
        internal static string Kick_AdminRequiredToKickAdmin {
            get {
                return ResourceManager.GetString("Kick_AdminRequiredToKickAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why would you want to kick yourself?.
        /// </summary>
        internal static string Kick_CannotKickSelf {
            get {
                return ResourceManager.GetString("Kick_CannotKickSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners cannot kick other owners. Only the room creator can kick an owner..
        /// </summary>
        internal static string Kick_CreatorRequiredToKickOwner {
            get {
                return ResourceManager.GetString("Kick_CreatorRequiredToKickOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to kick them from?.
        /// </summary>
        internal static string Kick_RoomRequired {
            get {
                return ResourceManager.GetString("Kick_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to to kick?.
        /// </summary>
        internal static string Kick_UserRequired {
            get {
                return ResourceManager.GetString("Kick_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to leave?.
        /// </summary>
        internal static string Leave_RoomRequired {
            get {
                return ResourceManager.GetString("Leave_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to list the current users of?.
        /// </summary>
        internal static string List_RoomRequired {
            get {
                return ResourceManager.GetString("List_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to lock?.
        /// </summary>
        internal static string Lock_RoomRequired {
            get {
                return ResourceManager.GetString("Lock_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You what?.
        /// </summary>
        internal static string Me_ActionRequired {
            get {
                return ResourceManager.GetString("Me_ActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t private message yourself!.
        /// </summary>
        internal static string Msg_CannotMsgSelf {
            get {
                return ResourceManager.GetString("Msg_CannotMsgSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to say to {0}?.
        /// </summary>
        internal static string Msg_MessageRequired {
            get {
                return ResourceManager.GetString("Msg_MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to send a private message to?.
        /// </summary>
        internal static string Msg_UserRequired {
            get {
                return ResourceManager.GetString("Msg_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room can only be nudged once every {0} seconds..
        /// </summary>
        internal static string NudgeRoom_Throttled {
            get {
                return ResourceManager.GetString("NudgeRoom_Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t nudge yourself!.
        /// </summary>
        internal static string NudgeUser_CannotNudgeSelf {
            get {
                return ResourceManager.GetString("NudgeUser_CannotNudgeSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can only be nudged once every {0} seconds..
        /// </summary>
        internal static string NudgeUser_Throttled {
            get {
                return ResourceManager.GetString("NudgeUser_Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to open?.
        /// </summary>
        internal static string Open_RoomRequired {
            get {
                return ResourceManager.GetString("Open_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not allowed to post a notification..
        /// </summary>
        internal static string PostNotification_NotAllowed {
            get {
                return ResourceManager.GetString("PostNotification_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which admin do you want to remove?.
        /// </summary>
        internal static string RemoveAdmin_UserRequired {
            get {
                return ResourceManager.GetString("RemoveAdmin_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which owner do you want to remove?.
        /// </summary>
        internal static string RemoveOwner_UserRequired {
            get {
                return ResourceManager.GetString("RemoveOwner_CommandUserMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to remove the owner from?.
        /// </summary>
        internal static string RemoveOwner_RoomRequired {
            get {
                return ResourceManager.GetString("RemoveOwner_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to reset the invite code of?.
        /// </summary>
        internal static string ResetInviteCode_RoomRequired {
            get {
                return ResourceManager.GetString("ResetInviteCode_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to {0}..
        /// </summary>
        internal static string RoomAccessPermission {
            get {
                return ResourceManager.GetString("RoomAccessPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t allowed to access {1}..
        /// </summary>
        internal static string RoomAccessPermissionUser {
            get {
                return ResourceManager.GetString("RoomAccessPermissionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already closed..
        /// </summary>
        internal static string RoomAlreadyClosed {
            get {
                return ResourceManager.GetString("RoomAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already locked..
        /// </summary>
        internal static string RoomAlreadyLocked {
            get {
                return ResourceManager.GetString("RoomAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already open..
        /// </summary>
        internal static string RoomAlreadyOpen {
            get {
                return ResourceManager.GetString("RoomAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby is not a valid chat room name..
        /// </summary>
        internal static string RoomCannotBeNamedLobby {
            get {
                return ResourceManager.GetString("RoomCannotBeNamedLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is closed..
        /// </summary>
        internal static string RoomClosed {
            get {
                return ResourceManager.GetString("RoomClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room creation is disabled..
        /// </summary>
        internal static string RoomCreationDisabled {
            get {
                return ResourceManager.GetString("RoomCreationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the creator of {0}..
        /// </summary>
        internal static string RoomCreatorRequired {
            get {
                return ResourceManager.GetString("RoomCreatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        internal static string RoomExists {
            get {
                return ResourceManager.GetString("RoomExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists, but it&apos;s closed..
        /// </summary>
        internal static string RoomExistsButClosed {
            get {
                return ResourceManager.GetString("RoomExistsButClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid room name..
        /// </summary>
        internal static string RoomInvalidName {
            get {
                return ResourceManager.GetString("RoomInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room names cannot contain spaces..
        /// </summary>
        internal static string RoomInvalidNameSpaces {
            get {
                return ResourceManager.GetString("RoomInvalidNameSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;/join room&apos; to join a room..
        /// </summary>
        internal static string RoomJoinMessage {
            get {
                return ResourceManager.GetString("RoomJoinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in {0}, but it doesn&apos;t exist..
        /// </summary>
        internal static string RoomMemberButNotExists {
            get {
                return ResourceManager.GetString("RoomMemberButNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0}..
        /// </summary>
        internal static string RoomNotFound {
            get {
                return ResourceManager.GetString("RoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not in {0}. Use &apos;/join {0}&apos; to join it..
        /// </summary>
        internal static string RoomNotMember {
            get {
                return ResourceManager.GetString("RoomNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a private room..
        /// </summary>
        internal static string RoomNotPrivate {
            get {
                return ResourceManager.GetString("RoomNotPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not an owner of {0}..
        /// </summary>
        internal static string RoomOwnerRequired {
            get {
                return ResourceManager.GetString("RoomOwnershipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No room specified..
        /// </summary>
        internal static string RoomRequired {
            get {
                return ResourceManager.GetString("RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name cannot be blank!.
        /// </summary>
        internal static string RoomNameCannotBeBlank {
            get {
                return ResourceManager.GetString("RoomRequiresName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already allowed into {1}..
        /// </summary>
        internal static string RoomUserAlreadyAllowed {
            get {
                return ResourceManager.GetString("RoomUserAlreadyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already an owner of {1}..
        /// </summary>
        internal static string RoomUserAlreadyOwner {
            get {
                return ResourceManager.GetString("RoomUserAlreadyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot post messages to {0}. The room is closed..
        /// </summary>
        internal static string SendMessageRoomClosed {
            get {
                return ResourceManager.GetString("SendMessageRoomClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved the settings..
        /// </summary>
        internal static string SettingsSaveSuccess {
            get {
                return ResourceManager.GetString("SettingsSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string SizeOrderBytes {
            get {
                return ResourceManager.GetString("SizeOrderBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string SizeOrderGB {
            get {
                return ResourceManager.GetString("SizeOrderGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string SizeOrderKB {
            get {
                return ResourceManager.GetString("SizeOrderKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string SizeOrderMB {
            get {
                return ResourceManager.GetString("SizeOrderMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot unallow an admin. Only admin can unallow admin..
        /// </summary>
        internal static string UnAllow_AdminRequired {
            get {
                return ResourceManager.GetString("UnAllow_AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why would you want to unallow yourself?.
        /// </summary>
        internal static string UnAllow_CannotUnallowSelf {
            get {
                return ResourceManager.GetString("UnAllow_CannotUnallowSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners cannot unallow other owners. Only the room creator can unallow an owner..
        /// </summary>
        internal static string UnAllow_CreatorRequiredToUnallowOwner {
            get {
                return ResourceManager.GetString("UnAllow_CreatorRequiredToUnallowOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which room do you want to revoke access from?.
        /// </summary>
        internal static string UnAllow_RoomRequired {
            get {
                return ResourceManager.GetString("UnAllow_RoomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who you want to revoke access permissions from?.
        /// </summary>
        internal static string UnAllow_UserRequired {
            get {
                return ResourceManager.GetString("UnAllow_UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload {0}..
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload {0}. {1}.
        /// </summary>
        internal static string UploadFailedException {
            get {
                return ResourceManager.GetString("UploadFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already an admin..
        /// </summary>
        internal static string UserAlreadyAdmin {
            get {
                return ResourceManager.GetString("UserAlreadyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid user name..
        /// </summary>
        internal static string UserInvalidName {
            get {
                return ResourceManager.GetString("UserInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} already taken..
        /// </summary>
        internal static string UserNameTaken {
            get {
                return ResourceManager.GetString("UserNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an admin..
        /// </summary>
        internal static string UserNotAdmin {
            get {
                return ResourceManager.GetString("UserNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0}..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t in {1}..
        /// </summary>
        internal static string UserNotInRoom {
            get {
                return ResourceManager.GetString("UserNotInRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an owner of {1}..
        /// </summary>
        internal static string UserNotRoomOwner {
            get {
                return ResourceManager.GetString("UserNotRoomOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View article.
        /// </summary>
        internal static string ViewArticle {
            get {
                return ResourceManager.GetString("ViewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Larger Map.
        /// </summary>
        internal static string ViewLargerMap {
            get {
                return ResourceManager.GetString("ViewLargerMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who do you want to locate?.
        /// </summary>
        internal static string Where_UserRequired {
            get {
                return ResourceManager.GetString("Where_UserRequired", resourceCulture);
            }
        }
    }
}
